### PR TITLE
Allows line ending override option for parse string

### PR DESCRIPTION
**Pull request by joshleecreates**

### CODE REVIEW

**Comment by josevalim** [comment]
@joshleecreates can you please tell us a bit more about this use case? "\r" is not a valid line ending unless something was stripping the new line before hand.

**Comment by joshleecreates** [comment]
@josevalim I know, it's super frustrating. I'm encountering `\r` line endings in a CSV files exported by excel for mac.

**Comment by josevalim** [comment]
@joshleecreates sorry to hear! :S Can we pass then `:newline` as an argument? This way we can do `:binary.compile_pattern(opts[:newline] || ["\r\n", "\n"])`. I don't want to introduce this behaviour to everyone if it applies only to one specific scenario. Thank you!

**Comment by joshleecreates** [comment]
@josevalim 👌 I'll update this PR momentarily

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment]
@joshleecreates sorry, I had to revert the changes because they did not work as expected. There are other places in the code assuming that a new line will be either "\r" or "\r\n" and those must be written at parser definition. I have pushed a proper commit to master, please give it a try.

**Pull request merged**
